### ISSUE TITLE
Can't change moderators of a forum

### ISSUE THREAD

**Issue by slider84** [XoopsModules25x/newbb#22]
it is not possible to change the moderators of a forum as it was created

**Comment by mambax7** [comment]
Cannot replicate in my branch. Please also include your steps, so I can try to follow your steps :)

My steps: 
1) go to Moderator's Tab (l/modules/newbb/admin/admin_groupmod.php) and select groups I want to allow to be moderators
2) Go to the Forum, and NewBB shows me all members from that Group(s). I can then leave all of them as Moderators, or I can select particular individual(s) from that group(s) to be the Moderator.

**Comment by slider84** [comment]
On your rc10 branch (29/09/2015)
My steps to reproduce this issue:
1- create a forum without moderators.
2- go to newbb home page. The forum is show without moderators (it's ok)
3- go to moderator's tab and assign a group of moderators to this forum.
4- Return to newbb home page (the forum is still show without moderators (not ok).
The smarty forum_moderators for this forum is empty but in the forum tab, moderators are well present in the list.

**Comment by mambax7** [comment]
I am not sure I understand the issue here. 
1) The moderators are visible in the Category view in the front view, and not in the Forum view, at least on my installation. 
2) I am able to change moderators in the Admin side, and the changes are visible in the Category view.

Therefore, what is the issue here:
a) you cannot change moderator from X-Person to Y-Person?  or
b) you want to see the moderators in the Forum view?
